# Policy Definitions & Assignments Spec
# Operator: policy
#
# ALZ Policy Initiatives based on official Azure Landing Zones reference:
# https://aka.ms/alz/policies

apiVersion: alz.azure.com/v1alpha1
kind: PolicySpec

metadata:
  name: alz-policy

spec:
  # Root management group for policy definitions
  managementGroupId: contoso  # CHANGE: Your root MG ID

  # ALZ Policy Initiatives - assigned at appropriate scopes
  # Reference: https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies
  initiatives:
    # === ROOT LEVEL POLICIES (apply to entire hierarchy) ===
    - name: Deploy-MDFC-Config
      displayName: Deploy Microsoft Defender for Cloud configuration
      scope: /providers/Microsoft.Management/managementGroups/contoso
      enforcementMode: Default
      description: Deploys and configures Microsoft Defender for Cloud settings

    - name: Deploy-Diagnostics-LogAnalytics
      displayName: Deploy Diagnostic Settings to Log Analytics
      scope: /providers/Microsoft.Management/managementGroups/contoso
      enforcementMode: Default
      description: Ensures all resources send diagnostics to central Log Analytics

    - name: Enforce-Guardrails
      displayName: Enforce ALZ Guardrails
      scope: /providers/Microsoft.Management/managementGroups/contoso
      enforcementMode: Default
      description: Core guardrails for security and compliance

    # === PLATFORM POLICIES ===
    - name: Deploy-Private-DNS-Zones
      displayName: Deploy Private DNS Zones
      scope: /providers/Microsoft.Management/managementGroups/connectivity
      enforcementMode: Default
      description: Deploys and configures Private DNS Zones for Private Endpoints

    # === LANDING ZONES POLICIES ===
    - name: Enforce-ALZ-Corp
      displayName: Enforce Corp Landing Zone policies
      scope: /providers/Microsoft.Management/managementGroups/corp
      enforcementMode: Default
      description: Policies for corporate workloads requiring hybrid connectivity

    - name: Enforce-ALZ-Online
      displayName: Enforce Online Landing Zone policies
      scope: /providers/Microsoft.Management/managementGroups/online
      enforcementMode: Default
      description: Policies for online workloads with internet connectivity

    # === SANDBOX POLICIES (less restrictive) ===
    - name: Enforce-ALZ-Sandbox
      displayName: Enforce Sandbox policies
      scope: /providers/Microsoft.Management/managementGroups/sandbox
      enforcementMode: Default
      description: Less restrictive policies for experimentation

    # === DECOMMISSIONED POLICIES (highly restrictive) ===
    - name: Enforce-ALZ-Decomm
      displayName: Enforce Decommissioned policies
      scope: /providers/Microsoft.Management/managementGroups/decommissioned
      enforcementMode: Default
      description: Deny all resource creation, prepare for deletion

  # Custom policy definitions (extend ALZ as needed)
  customDefinitions: []

  # Policy exemptions for specific resources/subscriptions
  exemptions: []

  tags:
    environment: production
    scenario: "6-single-region-hub-spoke-azfw"
    managedBy: azure-operator
    alzVersion: "2024-07"
