# Policy Definitions & Assignments Spec
# Operator: policy

apiVersion: alz.azure.com/v1alpha1
kind: PolicySpec

metadata:
  name: alz-policy

spec:
  # Scope for policy assignments
  managementGroupId: contoso  # CHANGE: Your root MG ID

  # Built-in ALZ policy initiatives to assign
  initiatives:
    - name: Deploy-MDFC-Config
      displayName: Deploy Microsoft Defender for Cloud configuration
      scope: /providers/Microsoft.Management/managementGroups/contoso
      enforcementMode: Default

    - name: Enforce-ALZ-Decomm
      displayName: Enforce policies for Decommissioned
      scope: /providers/Microsoft.Management/managementGroups/decommissioned
      enforcementMode: Default

    - name: Enforce-ALZ-Sandbox
      displayName: Enforce policies for Sandbox
      scope: /providers/Microsoft.Management/managementGroups/sandbox
      enforcementMode: Default

  # Custom policy definitions (if any)
  customDefinitions: []

  # Policy exemptions (if any)
  exemptions: []

  tags:
    environment: production
    scenario: "6-single-region-hub-spoke-azfw"
    managedBy: azure-operator
